---
# Server setup configuration
db:
  host: "localhost"
  user: "root"
  pass: "H6ih2PcqGwy4WjpmRwHZ"
  old_db: "TAED"
  new_db: "TAED_LIGHT"
files:
  flat: "./Bulk/TAED2/"
  blastdb: "./Bulk/TAED2/BLAST/"
  temp: "./Bulk/TAED2/"
defaults:
  max_hits: 50
  max_blasts: 5
  e_value: 1.0
