---
# Server setup configuration
db:
  host: "localhost"
  user: "root"
  pass: "H6ih2PcqGwy4WjpmRwHZ"
  old_db: "TAED"
  new_db: "TAED_LIGHT"
files:
  flat: "/var/www/TAED/"
  blast: "/var/www/TAED/BLAST/"
  temp: "/var/www/TAED/"
defaults:
  max_hits: 50
  max_blasts: 5
  e_value: 1.0
